stages:
  model:
    cmd: python scr/model.py --path=params.yaml
    deps:
    - data/raw/water_potability.csv
    - scr/model.py 
    params:
    - train
    - paths
    - loglevel
    outs:
    - models/model.pk
